# This workflow will do a clean install of node dependencies, build the source code and deploy it on hosting through FTP

name: Publish artifacts

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        local-dir: build/
        server-dir: /wordpress/public_html/frontend/
        ftp-server: opora66.ru
        ftp-username: cr63458_opora
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --all
